services:
  core-backend-db:
    image: postgis/postgis:latest
    container_name: core-backend-db
    environment:
      POSTGRES_DB: car_db
      POSTGRES_USER: car_user
      POSTGRES_PASSWORD: car_pass
    ports:
      - "5432:5432"
    volumes:
      - car-db-data:/var/lib/postgresql/data
    networks:
      - core-backend-network

  # core-backend_builder:
  #   image: gradle:8.12.1-jdk21
  #   container_name: core-backend_builder
  #   network_mode: "host"
  #   working_dir: /app
  #   volumes:
  #     - ./:/app
  #     - gradle-cache:/home/gradle/.gradle  # cache para dependências
  #   command: ./gradlew clean compileJasperReports copyCompiledJasper build -x test --no-daemon
  #   environment:
  #     - GRADLE_OPTS=-Dhttps.proxyHost= -Dhttps.proxyPort= -Dhttp.proxyHost= -Dhttp.proxyPort=
  #     - HTTP_PROXY=http://10.31.220.23:3128
  #     - HTTPS_PROXY=http://10.31.220.23:3128
  #     - NO_PROXY=localhost,127.0.0.1,gov.br,dataprev.gov.br
  #   restart: "no"

  # core-backend:
  #   image: eclipse-temurin:21-jre-jammy
  #   container_name: core-backend
  #   working_dir: /app
  #   depends_on:
  #     core-backend_builder:
  #       condition: service_completed_successfully
  #     core-backend-db:
  #       condition: service_started
  #   volumes:
  #     - gradle-cache:/home/gradle/.gradle
  #     - ./build:/app/build  # JAR gerado pelo builder
  #   command: java -jar ./build/libs/registration-0.0.1-SNAPSHOT.jar
  #   environment:
  #     SPRING_DATASOURCE_URL: "jdbc:postgresql://core-backend-db:5432/car_db"
  #     SPRING_DATASOURCE_USERNAME: car_user
  #     SPRING_DATASOURCE_PASSWORD: car_pass
  #     FRONTEND_URLS: http://localhost,http://localhost:5173
  #     HASH_PREFIX: BR
  #     RECEIPT_LOGO_PATH: images/govbr.svg
  #     GENERAL_INFORMATION_RECEIPT_PATH: reports/GENERAL_INFORMATION.txt
  #     REPORT_PARAMS_RECEIPT_JSON: reports/report_params.json
  #     HTTP_PROXY: 
  #     HTTPS_PROXY: 
  #     NO_PROXY: 
  #   networks:
  #     - core-backend-network
  #     # - frontend_network
  #     - gateway_network

  core-backend:
    image: rer-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: core-backend
    depends_on:
      - core-backend-db
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://core-backend-db:5432/car_db"
      SPRING_DATASOURCE_USERNAME: car_user
      SPRING_DATASOURCE_PASSWORD: car_pass
      FRONTEND_URLS: http://localhost,http://localhost:5173
      HASH_PREFIX: BR
      RECEIPT_LOGO_PATH: images/govbr.svg
      WATERMARK_IMAGE_PATH: images/unofficial.svg
      GENERAL_INFORMATION_RECEIPT_PATH: reports/GENERAL_INFORMATION.txt
      REPORT_PARAMS_RECEIPT_JSON: reports/report_params.json
      DEFAULT_LOCATION_ZONE: Europe/London
      HTTP_PROXY: 
      HTTPS_PROXY: 
      NO_PROXY: 
    networks:
      - core-backend-network
      - gateway_network

networks:
  core-backend-network:
    driver: bridge

volumes:
  car-db-data:
